#!/usr/bin/env python
"""
sample_test

autogenerated sample test for rq_examples
"""
import unittest
import rq_examples

class SampleTest(unittest.TestCase):
    """placeholder for real tests"""
    def test_sample(self):
        self.failUnless(True)



if __name__ == '__main__':
    unittest.main()